spring:
  data:
    mongodb:
      database: chat
      host: localhost
      port: 27017
      username: admin
      password: admin
      authentication-database: admin
      auto-index-creation: true
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
